---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: appmesh-inject
  namespace: appmesh-system
spec:
  releaseName: appmesh-inject
  chart:
    repository: https://aws.github.io/eks-charts/
    name: appmesh-inject
    version: 0.9.0
  values:
    mesh:
      create: true
      name: apps